# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bart <- function(x_train, y_train, x_test, n_tree, n_mcmc, n_burn, tau, mu, tau_mu, alpha, beta, a_tau, d_tau) {
    .Call('_sbart_bart', PACKAGE = 'sbart', x_train, y_train, x_test, n_tree, n_mcmc, n_burn, tau, mu, tau_mu, alpha, beta, a_tau, d_tau)
}

test_logtree <- function(X, y) {
    .Call('_sbart_test_logtree', PACKAGE = 'sbart', X, y)
}

rand_unif <- function() {
    .Call('_sbart_rand_unif', PACKAGE = 'sbart')
}

